-ifndef(VERNEMQ_DEV_HRL).
-define(VERNEMQ_DEV_HRL, true).
-define(true, 1).
-define(false, 0).
-type peer()                :: {inet:ip_address(), inet:port_number()}.
-type username()            :: binary() | undefined.
-type password()            :: binary() | undefined.
-type client_id()           :: binary().
-type mountpoint()          :: string().
-type subscriber_id()       :: {mountpoint(), client_id()}.
-type reg_view()            :: atom().
-type topic()               :: [binary()] | binary(). %% binary() for test purposes only.
-type qos()                 :: 0 | 1 | 2.
-type payload()             :: binary().
-type flag()                :: ?true | ?false | boolean() | empty. % empty for test purposes only
-endif.
